# Builds the addons for download. End user can import the zip into Godot.
# push a tag to build
on: 
  push:
   #branches: [godot-4.1.1]
   tags:
      - "v*"
jobs:
  # job id, can be anything
  export_game:
    runs-on: ubuntu-latest
    # Add permission for release creation.
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0

    - name: zip addons
      run: |
        7z a -tzip ""pingod-addons-(${{ github.ref_name }}).zip" "addons"
  
    #- name: export game
    #  id: export
    #  # Use latest version (see releases for all versions)
    #  uses: firebelley/godot-export@v5.2.0
    #  with:
    #    # Defining all the required inputs
    #    godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_linux_x86_64.zip
    #    godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_export_templates.tpz
    #    relative_project_path: ./
    #    archive_output: true

    #  # This release action has worked well for me. However, you can most likely use any release action of your choosing.
    #  # https://github.com/ncipollo/release-action
    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}        
        generateReleaseNotes: false
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*, pingod-addons-(${{ github.ref_name }}).zip